### ISSUE TITLE
Admin home does not work

### ISSUE THREAD

**Issue by danielacraciun** [robert-sandor/student_management#12]
Please rename the admin_home to home (function needs to be the same for all routes). Error I'm getting while accessing the route:
`werkzeug.routing.BuildError
werkzeug.routing.BuildError: Could not build url for endpoint 'admin_staff.home'. Did you mean 'admin_staff.admin_home' instead?`

**Comment by victorursan** [comment]
work on: "admin_mod"  branch

**Comment by victorursan** [comment]
:+1:
