### ISSUE TITLE
Template for Master/Detail Interface

### ISSUE THREAD

**Issue by alexandraatr** [robert-sandor/student_management#16]
We need to create the core template for all the pages of this app. The master/detail pattern should be used for this.
Basically we want something like this:
![patterns-masterdetail-400x227](https://cloud.githubusercontent.com/assets/12293406/14649614/894c9afe-0670-11e6-8c4c-9b3638f52ad3.png)

The side bar is different for each entity. The only two things they share are the settings page, and the home page (displaying different data, obviously). 
For each option in the sidebar, the content changes or a drop down menu appears (if there are multiple things related to the same option).

Info about the logged in user will be permanently displayed above the content ('detail' part).

**Comment by victorursan** [comment]
👍
